### PR TITLE
Add awaitable extractor functions.

### PR DESCRIPTION
**Pull request by kikijiki**
This lets me use it like `await Archive.ExtractArchiveAsync(path)`.

### CODE REVIEW

**Comment by TimzChen** [comment]
I have ported SevenZipSharp to .net 4.0 and .net standard 2.0, but it not support awaitable functions. Are you going to support .net4.0? And the awaitable functions can be added to a stand-alone project.

**Comment by squid-box** [comment]
I like this, would have been good with some unit tests. I will try this out a bit before merging the PR.

**Comment by kikijiki** [comment]
Thanks.

**Comment by kikijiki** [comment]
I noticed a problem with this implementation, exceptions are not getting rethrown.
For example in some code I have:

```csharp
try
{
    using(var archive = new SevenZip.SevenZipExtractor(zipPath))
    {
        await archive.ExtractArchiveAsync(outPath);
    }
}
catch(Exception ex)
{
    Console.Writeline(ex);
}
```

If one of the output files cannot be written (because already opened or locked by some process), no exception is caught.
If I change it like this instead, it gets handled correctly:

```csharp
// from
await archive.ExtractArchiveAsync(outPath);
// to
await Task.Run(() => archive.ExtractArchive(outPath));
```

**Pull request merged**
